(maint) Disconnect networks during teardown
 - In rare circumstances, shutting down containers doesn't work because
   they are still attached to networks. Error messages may appear like:

   Removing network pupperware-commercial
   ERROR: error while removing network: network pupperware-commercial id 007d116f17a16dc732171d02746b65d764008948d82f83133b1e7857edb91789 has active endpoints

 - As part of shutting down containers, forcibly disconnect them from
   their network first.